name: "allure-publish-action"
description: "Publish allure report to cloud provider"
author: "Andrejs"
branding:
  icon: "book-open"
  color: "yellow"
inputs:
  storageType:
    required: true
    description: "Cloud storage type"
  resultsGlob:
    required: true
    description: "Allure results files glob"
  bucket:
    required: true
    description: "Bucket name"
  prefix:
    required: false
    description: "Optional prefix for report path"
  baseUrl:
    required: false
    description: "Custom report base url"
  updatePr:
    required: false
    description: "Add result summary (pr or actions summary)"
    default: "actions"
  summary:
    required: false
    description: "Additionally add summary table of test results"
    default: "total"
  summaryTableType:
    required: false
    description: "Summary table type (ascii or markdown)"
    default: "markdown"
  collapseSummary:
    required: false
    description: "Create summary table as a collapsable section"
  reportTitle:
    required: false
    description: "Custom report title"
  copyLatest:
    required: false
    description: "Keep copy of latest report at base prefix path"
  ignoreMissingResults:
    required: false
    description: "Ignore missing allure results"
  flakyWarningStatus:
    required: false
    description: "Flaky test warning status"
  color:
    required: false
    description: "Force color output"
    default: "true"
  debug:
    required: false
    description: "Add debug log output"
    default: "false"
runs:
  using: docker
  image: Dockerfile
  args:
    - --results-glob=${{ inputs.resultsGlob }}
    - --bucket=${{ inputs.bucket }}
    - --prefix=${{ inputs.prefix }}
    - --update-pr=${{ inputs.updatePr }}
    - --summary=${{ inputs.summary }}
    - --summary-table-type=${{ inputs.summaryTableType }}
    - --collapse-summary=${{ inputs.collapseSummary }}
    - --report-title=${{ inputs.reportTitle }}
    - --copy-latest=${{ inputs.copyLatest }}
    - --ignore-missing-results=${{ inputs.ignoreMissingResults }}
    - --flaky-warning-status=${{ inputs.flakyWarningStatus }}
    - --color=${{ inputs.color }}
    - --base-url=${{ inputs.baseUrl }}
    - --debug=${{ inputs.debug }}
    - ${{ inputs.storageType }}
